name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # JDK 버전 설정
          distribution: 'adopt'  # JDK 배포판

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Build with Gradle(without tests)
        run: ./gradlew clean bootJar -x test
        working-directory: ./  # 루트 디렉토리로 설정

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ejy1024/travel-service:latest .

      - name: Push Docker image
        run: |
          docker push ejy1024/travel-service:latest
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key ec2-user@api.datecourse.net "docker pull ejy1024/travel-service:latest && docker run -d --rm ejy1024/travel-service:latest"
