name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # JDK 버전 설정
          distribution: 'adopt'  # JDK 배포판

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ./travel-service  # build.gradle 파일이 위치한 디렉토리로 설정

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ejy1024/travel-service:latest ./travel-service

      - name: Push Docker image
        run: |
          docker push ejy1024/travel-service:latest
