name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # JDK 버전 설정
          distribution: 'adopt'  # JDK 배포판

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Build with Gradle(without tests)
        run: ./gradlew clean bootJar -x test
        working-directory: ./  # 루트 디렉토리로 설정

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ejy1024/travel-service:latest .

      - name: Push Docker image
        run: |
          docker push ejy1024/travel-service:latest

      - name: Get Jenkins Crumb
        id: get_crumb
        run: |
          CRUMB=$(curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            http://${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb))
          echo "CRUMB=$CRUMB" >> $GITHUB_ENV

      - name: Trigger Jenkins Build
        run: |
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          -X POST "http://${{ secrets.JENKINS_URL }}/job/travel-backend/build" \
          -H "${{ env.CRUMB }}"
